### ISSUE TITLE
관리되지 않음

### ISSUE THREAD

**Issue by BasixKOR** [kdwkr/KKuTu#1]
끄투는 GPL 라이센스에 의해 배포되는 소프트웨어임에 비해, 끄투코리아의 소스코드는 현재까지 변경되고 있음이 사실상 확실한데도 2017년 9월 이후 전혀 업데이트가 이루어지지 않고 있습니다.

**Comment by kdwkr** [comment]
늦어서 죄송합니다.

**Comment by hatty163** [comment]
2018년 2월 이후 다시 관리가 되지 않고 있네요.. 빠른 해결 부탁드립니다.
