### ISSUE TITLE
Affero GPL

### ISSUE THREAD

**Issue by swoo5571** [kdwkr/KKuTu#11]
1월 1일 이후로 Affero GPL이 시행된걸로 알고있습니다.
끄투코리아 레포지토리가 업데이트가 안된 것을 보았습니다. 자체 개발 항목을 포함하여 레포지토리를 업데이트 하셔야합니다.

**Comment by kdwkr** [comment]
AGPL로 변경된 이후의 소스코드를 사용하고 있는것이 아니므로 바꿀 필요가 없습니다.
