### ISSUE TITLE
끄투코리아 리소스 사용에 대해

### ISSUE THREAD

**Issue by jhj1228** [kdwkr/KKuTu#12]
안녕하세요.

현재 레포지토리에 저장되어 있는 구버전의 레벨 이미지에 대해 문의할려고 하는데요. 현재는 레벨 이미지가 바뀌었음에도 구버전의 레벨 이미지의 저작권은 끄투코리아라는 것을 알고 있습니다.

따라서 현재 사용하고 있지 않는 구버전의 레벨 이미지를 사용해도 되는지 문의드렸습니다. 소스 사용 표기는 확실하게 할 것이고, 이미지의 저작권은 끄투코리아 라는 것을 단단히 명시하도록 하겠습니다.

감사합니다.

**Comment by kdwkr** [comment]
안녕하세요.

끄투코리아의 모든 리소스의 저작권은 모두 끄투코리아에 있으며, 사용이 불가능함을 알려드립니다.
관련하여 추가적인 문의사항이 있으실 경우 help@kkutu.co.kr 로 문의해주시면 감사하겠습니다.

고맙습니다.
